# Create dev group with sudo privileges + user
---
- name: create a non-root group
  group:
    name: "{{ group }}"
    state: present

- name: create non-root user
  user:
    name: "{{ user }}"
    group: "{{ group }}"
    shell: "/bin/bash"
    state: present

- name: add authorized_key to non-root user
  authorized_key:
    user: "{{ user }}"
    key: "{{ authorized_key }}"
    state: present
  when: not ansible_check_mode

- name: add non-root group to sudo privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{ group }}"
    line: "%{{ group }} ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s

# - name: disable root SSH logins
#   replace:
#     destfile: /etc/ssh/sshd_config
#     regexp: "^PermitRootLogin yes"
#     replace: "PermitRootLogin no"
#     backup: no

- name: disable SSH logins by password
  replace:
    destfile: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication yes"
    replace: "PasswordAuthentication no"
    backup: no

- name: restart SSH service
  service:
    name: ssh
    state: restarted
