# Recommended reading: https://ops.tips/blog/docker-ansible-role/

- name: Install list of packages
  apt:
    name: ["apt-transport-https", "ca-certificates", "curl", "gnupg2", "software-properties-common"]
    state: present
    update_cache: yes
  become: yes

- name: Add docker repo apt key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    state: "present"
  register: "add_repository_key"
  ignore_errors: true
  become: yes

- name: Add Docker APT repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: "present"
    update_cache: yes
  become: yes

- name: Install Docker and Docker-Compose
  apt:
    name: ["docker-ce", "docker-compose"]
    state: "present"
  become: yes

- name: Enable Docker systemd service
  service:
    name: "docker"
    state: "started"
    enabled: "yes"

- name: Add user to docker group
  user:
    name: "{{ user }}"
    groups: "docker"
    append: "yes"
  become: yes
